services:

  # Backend service
  backend:
    build: ./bams-backend
    container_name: bams-backend
    env_file:
      - ./bams-backend/.env
    ports:
      - "7788:8000"
    volumes:
      - ./bams-backend/app/ds/llm/utils:/app/app/ds/llm/utils


  # Frontend Service
  frontend:
    build: 
      context: ./bams-frontend
    container_name: bams-frontend
    env_file:
      - ./bams-frontend/.env
    ports:
      - "7777:5173"
    depends_on:
      - backend

  