"""add category to bank_accounts

Revision ID: 646e7a6164a1
Revises: 0a80ce77ddde
Create Date: 2026-08-10 12:32:06.116575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '646e7a6164a1'
down_revision: Union[str, Sequence[str], None] = '0a80ce77ddde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_accounts', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_accounts', 'category')
    # ### end Alembic commands ###
