"""add user_id fk to transactions, parsed, bank_accounts

Revision ID: ae363020da5e
Revises: 7531343749d2
Create Date: 2026-07-13 17:39:25.360973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae363020da5e'
down_revision: Union[str, Sequence[str], None] = '7531343749d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_accounts', sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False))
    op.alter_column('bank_accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    op.create_index(op.f('ix_bank_accounts_user_id'), 'bank_accounts', ['user_id'], unique=False)
    op.create_foreign_key(None, 'bank_accounts', 'users', ['user_id'], ['id'])
    op.add_column('parsed', sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False))
    op.alter_column('parsed', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    op.create_index(op.f('ix_parsed_user_id'), 'parsed', ['user_id'], unique=False)
    op.create_foreign_key(None, 'parsed', 'users', ['user_id'], ['id'])
    op.add_column('transactions', sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False))
    op.add_column('transactions', sa.Column('sheets_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-13 12:35:00.408636+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.drop_column('transactions', 'sheets_synced_at')
    op.drop_column('transactions', 'user_id')
    op.drop_constraint(None, 'parsed', type_='foreignkey')
    op.drop_index(op.f('ix_parsed_user_id'), table_name='parsed')
    op.alter_column('parsed', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-13 12:35:00.408636+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.drop_column('parsed', 'user_id')
    op.drop_constraint(None, 'bank_accounts', type_='foreignkey')
    op.drop_index(op.f('ix_bank_accounts_user_id'), table_name='bank_accounts')
    op.alter_column('bank_accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-13 12:35:00.408636+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.drop_column('bank_accounts', 'user_id')
    # ### end Alembic commands ###
