name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Code via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT || '22' }}
          script: |
            set -e

            cd ${{ secrets.DEPLOY_PATH }}

            git fetch origin main
            git reset --hard origin/main

            docker compose build
            docker compose up -d

            nohup docker compose logs -f backend > backend_output.log 2>&1 &
